### ISSUE TITLE
ask for source code

### ISSUE THREAD

**Issue by echolijinghui** [dmarnerides/hdr-expandnet#1]
Hello, I have been studying your paper recently. Can you share the training code? Thank you!

**Comment by dmarnerides** [comment]
Hey, thank you for the interest! 

I will be sharing the training code soon in a separate repo, so I'm closing this issue.

The training is fairly straightforward to implement from the paper, especially since the network definition is here and all augmentation can be done using openCV tone mappers. As for data, unfortunately I won't be able to share the dataset used, but there is a new (and most certainly higher quality) HDR dataset that can be used instead:

http://hdrplusdata.org/
