### ISSUE TITLE
The domain of pre-train model

### ISSUE THREAD

**Issue by vlee-harmonicinc** [dmarnerides/hdr-expandnet#8]
According to the paper, 
> All the images contained linear RGB values

Is the pre-model (./weights.pth) trained in linear RGB domain?
In this case, which domain is the input (image/video) of expand.py? It is assumed to be non-linear and processed to linear?

**Comment by dmarnerides** [comment]
Hi,
The inputs are non-linear RGB LDR images
Outputs are linear RGB HDR images.
All are in [0, 1] range.

Thanks

**Comment by vlee-harmonicinc** [comment]
Thank you for your quick response. :)
Is linear SDR - linear HDR also tested and verified that non-linear SDR input have better or similar result?

**Comment by dmarnerides** [comment]
The choice for non-linear SDR input is so that the method is fully end-to-end with no need to linearise first. However, linear SDR - linear HDR is not tested. I'm not sure how to do that though or if it's necessary, since we can't know the exact linearisation of the SDR (hence the gamma/tone mapping augmentation). Even applying a non-linearity can be considered tone mapping so it is encapsulated in the model.

Also, due to the nature of NNs, this linearisation of the SDR is not a problem, since they are highly expressive and non-linear functions. We can consider the linearisation as built-in the NN, without the need to explicitly define a separate step for it.
